### ISSUE TITLE
Unhandled rejection - 'Channel closed'

### ISSUE THREAD

**Issue by LadyAelita** [rkaw92/amqp-base#2]
The attempts to stop consumers by `AMQPListener` are possibly redundant and might be throwing exceptions that aren't being caught.

**Comment by rkaw92** [comment]
Just ran into this when it broke reconnection attempts of `AMQPConnector`. In short, what happened was:
* Connection event handler [1] runs
* We emit `disconnect`
* The subsequent lines should do a `setTimeout`, which never happens because some handler throws

In this instance, it's apparently the `AMQPListener` trying to cancel consumers [2] after the channel is closed and failing (as the channel is already closed!), which causes it to throw (synchronously!). This in turn bails us out before we get a chance to set up the reconnection timeout.

It looks like 2 things should be done to fully alleviate this (and prevent unhandled rejections):
* Defensive `try`/`catch` statements should be placed around all emits in `AMQPConnector`, possibly in all other classes as well
  * Alternatively, consider deferring the emits via `setImmediate`
* Redundant consumer cancels should be removed from `AMQPListener`.


[1] https://github.com/rkaw92/amqp-base/blob/707a7babed38040756cc9619288788e78b01d9b0/lib/AMQPConnector.js#L89
[2] https://github.com/rkaw92/amqp-base/blob/707a7babed38040756cc9619288788e78b01d9b0/lib/AMQPListener.js#L59
